version: "3.8"
services: 
  program:
    build: .
    container_name: program
    environment: 
    - NODE_ENV=development
    - CHOKIDAR_USEPOLLING=true
    - MEMORY_LIMIT=2048
    - MAX_THREADS=4
    env_file:
    - .env
    volumes: 
    - ./:/usr/src/app
    ports:
    - 8080:8080
    stdin_open: true
    tty: true
    command: sh /usr/src/app/entrypoint.sh