version: "3.8"
services: 
  program:
    build: .
    container_name: program
    environment: 
    - NODE_ENV=development
    - CHOKIDAR_USEPOLLING=true
<<<<<<< HEAD
    - MEMORY_LIMIT=8192
    # *Change threads depending on processing power/threads available
=======
    - MEMORY_LIMIT=2048
>>>>>>> fb9c89e3dae1afc86d81ac590046766739e5f430
    - MAX_THREADS=4
    env_file:
    - .env
    volumes: 
    - ./:/usr/src/app
    ports:
    - 8081:8080
    stdin_open: true
    tty: true
    command: sh /usr/src/app/entrypoint.sh