# This is a basic workflow that is manually triggered

name: 'Publish Graphql'

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [workflow_dispatch]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Publish Schema
        run: npx apollo service:push --graph=microapp --key=service:program:{{secrets.APOLLO_PROGRAM_SERVICE_KEY}} --variant=current --endpoint=https://us-west-2.aws.realm.mongodb.com/api/client/v2.0/app/program-otolc/graphql --header='apiKey:${{secrets.GRAPHQL_API_KEY}}'